ebkalderon/renderdoc-rs

renderdoc-sys/Cargo.toml

* Remove unused `readme` field so crate can build.

Remove unnecessary readme field from Cargo.toml

---

renderdoc-derive/Cargo.toml

* Remove `publish = false` from `renderdoc-derive` so `renderdoc` can be published.

Remove publish = false from renderdoc-derive Cargo.toml

---

src/api.rs

* Fix typo in method name in `RenderDocV111` trait so the crate builds.

Fix typo in RenderDocV111 trait

---

.circleci/config.yml

* Tentatively add nightly Rust in CI.
* Update stable commands so they aren't called through `rustup`.

Add nightly to CircleCI

---

Cargo.toml
README.md
renderdoc-derive/Cargo.toml
renderdoc-sys/Cargo.toml

* Add CI and documentation badges to `README.md`.
* Add CI badges to Cargo manifests.

Add CI and documentation badges

---

.circleci/config.yml
CHANGELOG.md
examples/triangle.rs
renderdoc-derive/src/lib.rs
src/api.rs
src/entry.rs

* Minor code reformatting tweaks.
* Switch to Circle CI Rust 1.33.0 image so CI can pass.

Reorder imports and run cargo fmt

---

CHANGELOG.md
src/api.rs

* Correct erroneous doc comments in `src/api.rs`.
Fixes #19.

Fix erroneous doc comments

---

CHANGELOG.md
renderdoc-derive/src/lib.rs
src/lib.rs

* Unimplement `Clone`, `Send`, and `Sync` traits for `RenderDoc` struct.
Fixes #25.
Fixes #26.

Fix some soundness bugs with RenderDoc struct

---

CHANGELOG.md
src/prelude.rs

* Add missing trait re-exports in `prelude` module.
Fixes #20.

Add missing trait re-exports in prelude module

---

CHANGELOG.md
src/api.rs

* Switch `set_capture_file_comments()` and `trigger_multi_frame_capture()` to take `&mut self`.
Fixes #27.
Fixes #28.

Switch internally mutating methods to &mut self

---

CHANGELOG.md
Cargo.toml
renderdoc-derive/Cargo.toml
renderdoc-sys/Cargo.toml

* Bump crate versions to 0.5.0.
* Update `CHANGELOG.md` to point to new release tag.

Prepare for release 0.5.0

---

README.md

* Remove obsolete `prelude::*` import from `README.md` example code.
This pull request is a follow-up to #35 and #36.

Remove obsolete prelude import from README.md

---

src/renderdoc.rs
src/version.rs

* Implement `Debug`, `Eq`, `Hash`, and `PartialEq` for `RenderDoc`.
* Implement `Copy`, `Clone`, `Eq`, `Hash`, `PartialEq` for `V###` types.
Fixes #21.

Manually implement Debug, derive Eq, Hash, and PartialEq

---

examples/triangle.rs
src/renderdoc.rs

* Mark `is_remote_access_connected()` as deprecated for all versions after 1.1.1.

Deprecate is_remote_access_connected() when using newer APIs

---

Cargo.toml
src/lib.rs
src/renderdoc.rs
src/version.rs

* Add `float_cmp` crate dependency.
* Add underscore separators to `SHADER_MAGIC_DEBUG_VALUE_TRUNCATED` constant.
* Use `float_cmp::ApproxEq` when comparing `f32` values.
* Use `as` casts for transmuting between `RenderDoc<V>` in `Deref` and `DerefMut` implementations.
* Remove unnecessary closure surrounding `std::ptr::null()` call.
* Eliminate `std::mem::transmute()` and `CStr::from_bytes_with_nul_unchecked()`
* Remove unnecessary closure surrounding `e.to_string()`.

Apply Clippy suggestions

---

src/renderdoc.rs

* Remove unused `prelude` module import from doc tests so they compile again.
The `prelude` module was previously removed from the project in #35.

Remove unused prelude module import from doc tests

---

.circleci/config.yml

* Change `cargo fmt` to `cargo fmt --all` in CircleCI.
* Switch minimum required Rust version in CircleCI to 1.31.0.
* Switch to custom Rust CircleCI image with RenderDoc ([ebkalderon/renderdoc-rs-circleci-dockerfile](https://github.com/ebkalderon/renderdoc-rs-circleci-dockerfile/)).
* Enable all unit tests and doc tests in CircleCI.
This pull request should allow all tests (including doc tests) to be compiled and run automatically before merging, preventing failure cases in CI like in #44 from happening again.

Switch to Rust 1.31 in CircleCI and enable all tests

---

CHANGELOG.md
Cargo.toml
renderdoc-derive/Cargo.toml
renderdoc-sys/Cargo.toml

* Bump crate versions to 0.6.0.
* Update `CHANGELOG.md` to point to new release tag.

Prepare for release 0.6.0

---

README.md
src/renderdoc.rs

* Add more doc tests: `downgrade()`, `launch_replay_ui()`, `is_remote_access_connected()`, `is_target_control_connected()`.
* Change `launch_replay_ui()` error value to `String` instead of `()` so it works with doc tests.
* Mark several doc tests that cannot be run in parallel as `no_run`.
* Rename "Example" sections to "Examples" in docs to match `std` conventions.
* Rename `init()` functions in doc tests to `main()` so they actually run in CI.
* Fix asserts in `get_api_version()` doc test and `README.md` example code so they account for forward-compatible API selection.

Fix main function for doc tests

---

renderdoc-derive/Cargo.toml
renderdoc-derive/src/lib.rs

* Upgrade `syn` dependency in `renderdoc-derive` from version 0.15.34 to 1.0.1.
* Upgrade `proc-macro2` dependency in `renderdoc-derive` from version 0.4.30 to 1.0.0.
* Upgrade `quote` dependency in `renderdoc-derive` from version 0.6.12 to 1.0.0.
* Accommodate for upstream API breakage in `syn` and `proc-macro2` in `renderdoc-derive`.
Closes #52.
Closes #53.
Closes #54.

Upgrade syn, quote, and proc-macro2 to 1.0

---

Cargo.toml
renderdoc-derive/Cargo.toml
src/lib.rs
src/renderdoc.rs

* Create `impl_from_versions!()` macro in `renderdoc.rs` to replace `renderdoc-derive` procedural macro.
* Bump `renderdoc-derive` crate version to 0.7.0, mark deprecated.
* Remove main crate dependency on `renderdoc-derive`.

Deprecate renderdoc-derive crate

---

src/renderdoc.rs

* Correct doc comment for `impl_from_versions!()` macro.

Correct erroneous doc comment

---

src/settings.rs

* Use `renderdoc-sys` values to define `CaptureOptions` and `InputButton` enums.
* Use `renderdoc-sys` values to define `OverlayBits` bitflags.

Use renderdoc-sys to define all settings enums

---

src/renderdoc.rs

* Clean up `rustdoc` output for `RenderDoc` struct by marking its `Deref` implementation as `#[doc(hidden)]`.
This should just be a cosmetic change and not affect the visibility rules in code editors relying on RLS or `rust-analyzer`.

Hide duplicate Deref methods from rustdoc for readability

---

src/handles.rs
src/lib.rs

* Repair broken Windows build by moving `wio` import to correct module.
Closes #60.
CC @retep998

Fix broken Windows build

---

CHANGELOG.md
Cargo.toml

* Bump main `renderdoc` crate version to 0.7.0.
* Update `CHANGELOG.md` with latest changes.

Prepare for release 0.7.0

---

CHANGELOG.md
renderdoc-derive/Cargo.toml

* Add empty workspace key to the `Cargo.toml` of `renderdoc-derive`.
* Tweak wording of `CHANGELOG.md`.

Minor tweaks made during release process

---

README.md
renderdoc-sys/README.md

* Simplify badge Markdown in `README.md` for `renderdoc` crate.
* Simplify badge Markdown in `README.md` for `renderdoc-sys` crate.

Simplify badge Markdown in README files

---

.circleci/config.yml

* Switch to Rust 1.36 in CircleCI to fix upstream `stb_truetype` 0.3.0 breakage.
See ebkalderon/renderdoc-rs-circleci-dockerfile#3 for details.

Switch to Rust 1.36 in CircleCI

---

CHANGELOG.md
Cargo.toml

* Update `CHANGELOG.md`.
* Bump `renderdoc` crate version to 0.7.1.

Prepare for release 0.7.1

---

LICENSE-MIT

* Update the copyright year in `LICENSE-MIT` to the current year.
The copyright year range is not necessary in this document since U.S. copyright law does not officially recognize year ranges, and the historical year values are retained safely in Git.

Update copyright year in LICENSE-MIT

---

.circleci/config.yml

* Fix CircleCI issues with `Cargo.lock` format incompatibility.
Seems like there is an incompatibility with the `Cargo.lock` files generated between older and newer versions of Rust (most likely the new merge-friendly format), which is affecting CircleCI in recent PRs (see #75).
This commit should hopefully allow us to start with an old lockfile, test our changes on stable, and then subsequently upgrade to the new lockfile format with nightly.

Build with stable Rust before building with Nightly

---

Cargo.toml
src/error.rs
src/lib.rs
src/renderdoc.rs
src/version.rs

* Add common `Error` type to use throughout the library.
* Return `PathBuf` from `get_capture()` instead of `String`.
* Return `&Path` from `get_{log,capture}_file_path_template()` instead of `&str`.
* Accept `Into<PathBuf>` or `Into<String>` in some places to avoid extra allocation if possible.
* Document if `path` argument is `None` in docs for `set_capture_file_comments()`.
* Switch from `lazy_static` to `once_cell`.
These changes were long overdue, and this crate hasn't seen any love in years. It's time to change that!

Improve type ergonomics and add Error type

---

src/renderdoc.rs

* Add `#[deprecated]` attributes to `get_log_file_path_template()` and `set_log_file_path_template()`.
* Move deprecated methods to bottom of `impl` blocks so they appear last in `rustdoc`.
These methods should rightfully be marked deprecated in 1.1.2 or higher. Leaving these methods un-annotated was technically an oversight, albeit a backwards-compatible one.

Mark log_file_path_template() methods deprecated in 1.1.2

---

Cargo.toml
src/lib.rs
src/renderdoc.rs
src/settings.rs
src/version.rs

* Convert to Rust 2018 edition. Given that we have finally found a reason to increase the minimum supported version to 1.40.0 with #78, and we can't support older compilers anyway, this should be perfectly safe to do.

Convert to Rust 2018 edition

---

CHANGELOG.md

* Correct `*_template_path()` to `*_path_template()` in description of `CHANGELOG.md`.
This mistake is associated with [release 0.8.0](https://github.com/ebkalderon/renderdoc-rs/releases/v0.8.0).

Fix incorrect method names in CHANGELOG.md

---

README.md
src/lib.rs
src/renderdoc.rs

* Fix copy-paste documentation error for `end_frame_capture()`.
* Fix formatting for `unload_crash_handler()` docs.
* Fix subtle spacing issue around `$PATH` in docs.

Fix some minor documentation errors

---

Cargo.toml
renderdoc-sys/Cargo.toml
renderdoc-sys/src/bindings.rs
src/renderdoc.rs
src/version.rs

* Define `V141` and `Version::V141` types.
* Add `remove_hooks()` method to `RenderDoc<V141>`, replacing `shutdown()`.
* Regenerate bindings to support API 1.4.1.
* Deprecate `shutdown()` for `RenderDoc<V141>` and newer.
* Add upstream compatibility disclaimer to `shutdown()` and `remove_hooks()`.
* Bump `renderdoc-sys` crate version to 0.7.0.

Support in-application API 1.4.1

---

src/renderdoc.rs

* Restore `shutdown()` method to the `RenderDoc<V: Version>` impl block.
* Remove `remove_hooks()` and `RenderDoc<V141>` impl block for now.
The previous changes from #91, moving `shutdown()` to the specific `RenderDoc<V100>` impl block and the addition of `remove_hooks()` to `RenderDoc<V141>`, won't actually work as intended in practice.
This is because the existing `Deref` and `DerefMut` implementations are not sufficient for either method to work properly. This would require the introduction of a `DerefMove` trait in the standard library to work (see https://github.com/rust-lang/rfcs/issues/997 for details).

Fix semantics of shutdown(), remove remove_hooks() for now

---

Cargo.toml
examples/triangle.rs
src/handles.rs
src/settings.rs

* Upgrade to `glutin` 0.24.
* Disable `glutin` integration by default.
Considering that `glutin` isn't necessary for `wgpu-rs` and isn't tightly integrated like it used to be with `gfx` pre-`ll`, this integration is turned off by default to avoid dragging in unnecessary dependencies.

Upgrade to glutin 0.24 and turn integration off by default

---

CHANGELOG.md
Cargo.toml

* Update `CHANGELOG.md`.
* Bump `renderdoc` crate version to 0.9.0.

Prepare release 0.9.0

---

Cargo.toml

* Enable all features when building for Docs.rs. This is done in order to showcase the `glutin` integration, if the feature is enabled by the user.

Enable all features when building for Docs.rs

---

README.md

* Remove `extern crate` from `README` example.
Since the 2018 edition has been mainstream for quite a while, we should update the `README.md` to reflect that.

Remove extern crate from README example

---

renderdoc-sys/Cargo.toml

* Exclude the `vendor` subdirectory from the `renderdoc-sys` crate.

Exclude extra files and dirs from crates

---

README.md

* Fix example in `README.md` by switching to `{:?}` format string.
Since `get_capture()` was changed in #86 to return an `std::time::SystemTime` representing the timestamp instead of a plain `u64`, the example code in the README no longer compiles due to this type not implementing `Display`.

Fix get_capture() example in README.md

---

README.md

* Tweak `expect()` message for clarity.
* Pattern match against `Option<(_, _)>`.

Minor README example improvements

---

CHANGELOG.md
Cargo.toml
renderdoc-sys/Cargo.toml
src/lib.rs
src/renderdoc.rs

* Allow global synchronized access (`Send` + `!Sync`) to RenderDoc (see #79).
* Minor stylistic improvements.
* Update `CHANGELOG.md`.
* Bump `renderdoc-sys` crate to 0.7.1.
* Bump `renderdoc` crate to 0.9.0.
* Expose `V141` version selector, which should have been done in `renderdoc` 0.9.0.

Prepare release 0.9.1

---

README.md

* Crate is dual-licensed under _either_ the MIT or Apache 2.0 licenses, at the user's option, not both simultaneously.

Clarify wording of README license disclaimer

---

CHANGELOG.md
Cargo.toml

* Update `RELEASE.md`.
* Bump `renderdoc` crate version to 0.10.0.

Prepare release 0.10.0

---

CHANGELOG.md
Cargo.toml

* Update `CHANGELOG.md`.
* Bump `renderdoc` crate version to 0.10.1.

Prepare release 0.10.1

---

.circleci/config.yml

* Switch to Rust 1.48.0 in CircleCI to make #110 pass in CI.
Related to https://github.com/ebkalderon/renderdoc-rs-circleci-dockerfile/pull/6.

Switch to Rust 1.48.0 in CircleCI

---

src/renderdoc.rs

I'm sure the docs meant to say that the functions must be paired with each other. Right now it's a bit misleading

Updated start_frame_capture(), end_frame_capture()

---

.circleci/config.yml

* Update CircleCI timezone from `Asia/Singapore` to `America/New_York`.
* Clear CircleCI project cache.
* Use new [ebkalderon/renderdoc-rs-circleci-dockerfile](https://github.com/ebkalderon/renderdoc-rs-circleci-dockerfile) image with Rust 1.51.0 to fix breaking builds.

Fix broken CircleCI config

---

.github/workflows/ci.yml
Cargo.toml

* Re-add missing `winit` 0.27 dev-dependency to fix triangle example.
* Check all examples compile in GitHub Actions, so this does not slip through again.

Fix triangle example by adding missing dev-dependency

---

Cargo.toml
examples/triangle.rs
src/version.rs

* Use `RTLD_NOLOAD` when loading `librenderdoc.so` on Unix.
* Use `GetModuleHandle` when loading `renderdoc.dll` on Windows.
Closes #128.

Fix loading of renderdoc library

---

src/renderdoc.rs

There are two issues in the `get_capture` function
- it assumes the file name will fit into 128 characters and overruns the allocated buffer otherwise
- it's using [`CString::from_raw`](https://doc.rust-lang.org/std/ffi/struct.CString.html#method.from_raw) incorrectly (see the safety section in the rust docs)
This PR fixes both.
The second issue was causing crashes with `STATUS_HEAP_CORRUPTION` for me because it did some funky things when trying to de-allocate the `CString` (I think it double-frees and the second free also uses the wrong layout; didn't look into it more).
I know you're currently rewriting most of the library but I wanted to share this anyway in case anyone else runs into the same crash.

Fix undefined behavior and crash in `get_capture`

---

CHANGELOG.md
Cargo.toml
renderdoc-sys/Cargo.toml

* Bump `renderdoc-sys` crate version to 1.1.0.
* Bump `renderdoc` crate version to 0.12.1.
* Because the changes in `renderdoc-sys` between 1.0.0 and 1.1.0 are entirely additive and do not impact the outward-facing API of the `renderdoc` crate at all, it should be safe to bump the patch version number here instead of the minor version.
* Update `CHANGELOG.md`

Prepare release 0.12.1
